version: 2.1

jobs:
  build:
    working_directory: ~/simple-react
    docker:
      - image: cimg/node:16.12.0
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - .yarn/cache
            - .yarn/unplugged
      - run:
          name: Run Tests
          command: yarn run test
      - run:
          name: Run Yarn Build
          command: yarn build
      - run:
          name: pwd
          command: pwd
      - run:
          name: ls
          command: ls
      - run:
          name: Build Container Image
          command: docker build -t simple-react .