version: 2.1

jobs:
  build:
    working_directory: ~/simple-react
    docker:
      - image: circleci/node:16.12.0
        auth:
          username: teetirat
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - restore_cache:
          keys:
            - yarn-packages-v1-{{ checksum "yarn.lock" }}
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn --frozen-lockfile --cache-folder ~/.cache/yarn && yarn install
      - run:
          name: Run Tests
          command: yarn run test
      - run:
          name: Run Yarn Build
          command: yarn build
      - run:
          name: Build Container Image
          command: docker build -t simple-react .