version: 2.1

executors:
  ci:
    environment:
      IMAGE_NAME: teetirat/simple-react
    docker:
      - image: circleci/node:16.12.0
        auth:
          username: teetirat
          password: $DOCKER_PASSWORD
    working_directory: ~/simple-react

jobs:
  test:
    executor: ci
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-v4-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-v4-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Run Tests
          command: yarn run test
  build-and-pack-image:
    executor: ci
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-v4-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-v4-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Build App
          command: yarn build
      - setup_remote_docker:
        version: 20.10.7
      - run:
          name: Build Container Image
          command: docker build -t simple-react .
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "teetirat" --password-stdin
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$SIMPLE_REACT_VERSION
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:latest
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$SIMPLE_REACT_VERSION
workflows:
  version: 2.1
  build-master:
    jobs:
      - test:
          filters:
            branches:
              only: main
      - build-and-pack-image:
          requires:
            - test
          filters:
            branches:
              only: main